definitions:
  github_com_rickyroynardson_image-go_internal_database.ImageStatus:
    enum:
    - pending
    - processing
    - completed
    - failed
    type: string
    x-enum-varnames:
    - ImageStatusPending
    - ImageStatusProcessing
    - ImageStatusCompleted
    - ImageStatusFailed
  github_com_rickyroynardson_image-go_internal_utils.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  github_com_rickyroynardson_image-go_internal_utils.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  internal_auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  internal_auth.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/internal_auth.User'
    type: object
  internal_auth.RefreshResponse:
    properties:
      access_token:
        type: string
    type: object
  internal_auth.RegisterRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      password:
        type: string
    required:
    - confirm_password
    - email
    - password
    type: object
  internal_auth.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      updated_at:
        type: string
    type: object
  internal_batch.BatchResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      images:
        items:
          $ref: '#/definitions/internal_batch.ImageResponse'
        type: array
      name:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
      watermark_key:
        type: string
      watermark_url:
        type: string
    type: object
  internal_batch.BatchesResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      image_completed_count:
        type: integer
      image_count:
        type: integer
      image_failed_count:
        type: integer
      image_pending_count:
        type: integer
      image_processing_count:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
      watermark_key:
        type: string
      watermark_url:
        type: string
    type: object
  internal_batch.ImageResponse:
    properties:
      batch_id:
        type: string
      created_at:
        type: string
      id:
        type: string
      key:
        type: string
      original_url:
        type: string
      processed_url:
        type: string
      status:
        $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_database.ImageStatus'
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /batches:
    get:
      description: Retrieve all batches for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/internal_batch.BatchesResponse'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get list of batches
      tags:
      - batches
    post:
      consumes:
      - multipart/form-data
      description: Create a new batch with images and optional watermark
      parameters:
      - description: Batch name
        in: formData
        name: name
        type: string
      - description: Image files (multiple)
        in: formData
        name: files
        required: true
        type: file
      - description: Watermark image file
        in: formData
        name: watermark
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.SuccessResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create batch
      tags:
      - batches
  /batches/{batchID}:
    delete:
      description: Delete a specific batch by its ID for the authenticated user
      parameters:
      - description: Batch ID
        in: path
        name: batchID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.SuccessResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete batch by ID
      tags:
      - batches
    get:
      description: Retrieve a specific batch by its ID for the authenticated user
      parameters:
      - description: Batch ID
        in: path
        name: batchID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/internal_batch.BatchResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get batch by ID
      tags:
      - batches
  /images/{imageID}:
    delete:
      description: Delete an image by its ID for the authenticated user
      parameters:
      - description: Image ID
        in: path
        name: imageID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.SuccessResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete an image by ID
      tags:
      - images
  /login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Login Request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/internal_auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/internal_auth.LoginResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
      summary: Login
      tags:
      - authentication
  /refresh:
    post:
      consumes:
      - application/json
      description: Refresh access token using refresh token (can be provided as cookie
        or Authorization header)
      parameters:
      - description: Bearer Token (refresh token)
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/internal_auth.RefreshResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
      summary: Refresh access token
      tags:
      - authentication
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Register Request
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/internal_auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/internal_auth.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rickyroynardson_image-go_internal_utils.ErrorResponse'
      summary: Register
      tags:
      - authentication
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
